"""
Django settings for speakpro project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ===========================
# BASIC SETTINGS
# ===========================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-i^b1(h79#a5&%h7^zg$=h6_189%%)2r@$+32kvs1&i8r*fc*qm"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

#: tăng giới hạn upload (nếu bạn cần upload file lớn)
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024


# ===========================
# CORS
# ===========================

# Dev cho nhanh: cho phép tất cả origin
CORS_ALLOW_ALL_ORIGINS = True

# Nếu sau này muốn giới hạn FE cụ thể, bỏ CORS_ALLOW_ALL_ORIGINS và dùng list này:
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8080",
]


# ===========================
# MEDIA
# ===========================

MEDIA_URL = "/media/"

MEDIA_ROOT = os.path.join(BASE_DIR, "app", "media")
# MEDIA_ROOT = os.path.join(BASE_DIR, "app", "media")


# ===========================
# APPLICATION DEFINITION
# ===========================

INSTALLED_APPS = [
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "rest_framework_simplejwt.token_blacklist",

    # Local app
    "app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # Nên đặt CORS middleware sớm
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "travles.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # nếu có templates chung thì add vào đây
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
"django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "travles.wsgi.application"


# ===========================
# DATABASE
# ===========================


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'travels',  
        'USER': 'root',   
        'PASSWORD': '123456',  
        'HOST': 'localhost',      
        'PORT': '3307',           
    }
}


# ===========================
# PASSWORD VALIDATION
# ===========================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ===========================
# INTERNATIONALIZATION
# ===========================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"  # hoặc "Asia/Ho_Chi_Minh" nếu muốn

USE_I18N = True
USE_TZ = True


# ===========================
# STATIC & MEDIA
# ===========================

STATIC_URL = "static/"

# Static root (dùng khi collectstatic lúc deploy, dev thì không bắt buộc)
STATIC_ROOT = BASE_DIR / "staticfiles"


# ===========================
# DEFAULT PRIMARY KEY FIELD TYPE
# ===========================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ===========================
# DRF & JWT
# ===========================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}


# ===========================
# EMAIL
# ===========================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
REST_FRAMEWORK = {
        'DEFAULT_AUTHENTICATION_CLASSES': (
            'rest_framework_simplejwt.authentication.JWTAuthentication',
        ),
}    
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}    