# Generated by Django 5.1.1 on 2025-12-23 12:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='ten', max_length=255)),
                ('short_description', models.TextField(blank=True, db_column='mo_ta_ngan')),
                ('location', models.CharField(blank=True, db_column='khu_vuc', max_length=255)),
                ('latitude', models.FloatField(blank=True, db_column='vi_do', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='kinh_do', null=True)),
                ('image_url', models.URLField(blank=True, db_column='url_anh', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ngay_tao')),
            ],
            options={
                'db_table': 'diemden',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='ma_iata', help_text='Mã IATA, ví dụ DAD, SGN', max_length=3, unique=True)),
                ('name', models.CharField(db_column='ten', max_length=255)),
                ('city', models.CharField(blank=True, db_column='thanh_pho', max_length=255)),
                ('country', models.CharField(blank=True, db_column='quoc_gia', max_length=255)),
            ],
            options={
                'db_table': 'sanbay',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='sanbay_ma_iata_2a6d8e_idx'), models.Index(fields=['city'], name='sanbay_thanh_p_c45507_idx'), models.Index(fields=['country'], name='sanbay_quoc_gi_d8fedb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='tieu_de', max_length=255)),
                ('summary', models.TextField(blank=True, db_column='tong_quan')),
                ('total_days', models.PositiveSmallIntegerField(db_column='so_ngay', help_text='Tổng số ngày trong lịch trình')),
                ('budget_min', models.DecimalField(blank=True, db_column='chi_phi_tu', decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, db_column='chi_phi_den', decimal_places=2, max_digits=12, null=True)),
                ('travel_style', models.CharField(blank=True, db_column='phong_cach', help_text='Ví dụ: nghỉ dưỡng, khám phá, ẩm thực...', max_length=50)),
                ('source_type', models.CharField(choices=[('sample', 'Lịch trình mẫu'), ('ai', 'Lịch trình AI gợi ý'), ('custom', 'Lịch trình tùy chỉnh')], db_column='nguon', default='sample', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Công khai'), ('archived', 'Lưu trữ')], db_column='trang_thai', default='published', max_length=20)),
                ('is_fixed', models.BooleanField(db_column='co_dinh', default=False, help_text='Lịch trình mẫu cố định, chỉ admin được sửa')),
                ('is_public', models.BooleanField(db_column='cong_khai', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ngay_tao')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='ngay_cap_nhat')),
                ('base_itinerary', models.ForeignKey(blank=True, db_column='lichtrinh_goc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_itineraries', to='app.itinerary')),
                ('main_destination', models.ForeignKey(blank=True, db_column='diemden_chinh', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_itineraries', to='app.destination')),
                ('user', models.ForeignKey(blank=True, db_column='nguoidung', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lichtrinh',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(db_column='ngay', help_text='Ngày thứ mấy trong lịch trình (1,2,3,...)')),
                ('part_of_day', models.CharField(choices=[('morning', 'Buổi sáng'), ('afternoon', 'Buổi chiều'), ('evening', 'Buổi tối'), ('full_day', 'Cả ngày')], db_column='buoi', max_length=20)),
                ('activity_title', models.CharField(blank=True, db_column='tieu_de_hoat_dong', max_length=255)),
                ('activity_description', models.TextField(blank=True, db_column='mo_ta_hoat_dong')),
                ('order', models.PositiveIntegerField(db_column='thu_tu', default=1, help_text='Thứ tự trong cùng 1 buổi của ngày đó')),
                ('destination', models.ForeignKey(db_column='diemden', on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_destinations', to='app.destination')),
                ('itinerary', models.ForeignKey(db_column='lichtrinh', on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_destinations', to='app.itinerary')),
            ],
            options={
                'db_table': 'lichtrinh_diemden',
                'ordering': ['itinerary', 'day_number', 'part_of_day', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destinations',
            field=models.ManyToManyField(blank=True, related_name='itineraries', through='app.ItineraryDestination', to='app.destination'),
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ten', help_text='Tên sở thích: beach, mountain, foodie, nightlife, museum…', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'so_thich',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='so_thich_ten_c1949a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatTurn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_user', models.TextField(db_column='noi_dung_nguoi_dung')),
                ('text_ai', models.TextField(db_column='noi_dung_ai')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ngay_tao')),
                ('user', models.ForeignKey(blank=True, db_column='nguoidung', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'luot_chat',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['created_at'], name='luot_chat_ngay_ta_2276c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlightSegment',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('airline', models.CharField(blank=True, db_column='hang_bay', max_length=255)),
                ('flight_number', models.CharField(blank=True, db_column='so_hieu', max_length=50)),
                ('departure_time', models.DateTimeField(db_column='gio_di')),
                ('arrival_time', models.DateTimeField(db_column='gio_den')),
                ('price', models.DecimalField(blank=True, db_column='gia', decimal_places=2, max_digits=12, null=True)),
                ('destination_airport', models.ForeignKey(db_column='sanbay_den', on_delete=django.db.models.deletion.CASCADE, related_name='chang_den', to='app.airport')),
                ('origin_airport', models.ForeignKey(db_column='sanbay_di', on_delete=django.db.models.deletion.CASCADE, related_name='chang_di', to='app.airport')),
            ],
            options={
                'db_table': 'chang_bay',
                'ordering': ['-departure_time', 'id'],
                'indexes': [models.Index(fields=['origin_airport'], name='chang_bay_sanbay__ef178b_idx'), models.Index(fields=['destination_airport'], name='chang_bay_sanbay__2d21e5_idx'), models.Index(fields=['departure_time'], name='chang_bay_gio_di_706136_idx'), models.Index(fields=['airline'], name='chang_bay_hang_ba_ca390e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItineraryReview',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(db_column='so_sao', help_text='Số sao 1-5 cho cả lịch trình', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, db_column='noi_dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ngay_tao')),
                ('itinerary', models.ForeignKey(db_column='lichtrinh', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.itinerary')),
                ('user', models.ForeignKey(db_column='nguoidung', on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'danhgia',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['itinerary'], name='danhgia_lichtri_eb4e92_idx'), models.Index(fields=['user'], name='danhgia_nguoidu_56ba4e_idx'), models.Index(fields=['created_at'], name='danhgia_ngay_ta_e8a5ed_idx'), models.Index(fields=['rating'], name='danhgia_so_sao_a09285_idx')],
                'constraints': [models.UniqueConstraint(fields=('itinerary', 'user'), name='uniq_danhgia_lichtrinh_nguoidung')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(db_column='id_dich_vu', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ten_dich_vu', max_length=255)),
                ('service_type', models.CharField(choices=[('hotel', 'Khách sạn'), ('food', 'Ăn uống'), ('spa', 'Spa'), ('activity', 'Vui chơi/Hoạt động'), ('shopping', 'Mua sắm'), ('other', 'Khác')], db_column='loai_dich_vu', default='food', max_length=50)),
                ('description', models.TextField(blank=True, db_column='mo_ta')),
                ('address', models.CharField(blank=True, db_column='dia_chi', max_length=255)),
                ('price_from', models.DecimalField(blank=True, db_column='gia_tu', decimal_places=2, max_digits=12, null=True)),
                ('price_range', models.CharField(blank=True, db_column='gia_tham_khao', max_length=100, null=True)),
                ('rating_avg', models.DecimalField(db_column='diem_danh_gia_tb', decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rating_count', models.PositiveIntegerField(db_column='so_luot_danh_gia', default=0)),
                ('image_url', models.URLField(blank=True, db_column='hinh_anh', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ngay_tao')),
                ('destination', models.ForeignKey(db_column='diem_den_id', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app.destination')),
            ],
            options={
                'db_table': 'dich_vu',
                'ordering': ['destination', 'name'],
                'indexes': [models.Index(fields=['destination'], name='dich_vu_diem_de_0b5c22_idx'), models.Index(fields=['service_type'], name='dich_vu_loai_di_fc3b2b_idx'), models.Index(fields=['created_at'], name='dich_vu_ngay_ta_cb30e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('preference', models.ForeignKey(db_column='so_thich', on_delete=django.db.models.deletion.CASCADE, related_name='nguoidung_so_thich', to='app.preference')),
                ('user', models.ForeignKey(db_column='nguoidung', on_delete=django.db.models.deletion.CASCADE, related_name='so_thich_nguoidung', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nguoidung_so_thich',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['user'], name='nguoidung_s_nguoidu_b46db2_idx'), models.Index(fields=['preference'], name='nguoidung_s_so_thic_b17fa7_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'preference'), name='uniq_nguoidung_so_thich')],
            },
        ),
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(db_column='thang', help_text='Tháng trong năm (1-12)')),
                ('note', models.TextField(blank=True, db_column='ghi_chu', help_text='Ghi chú tổng quan: nên đi/không nên đi, thời tiết thế nào')),
                ('destination', models.ForeignKey(db_column='diemden', on_delete=django.db.models.deletion.CASCADE, related_name='weather_infos', to='app.destination')),
            ],
            options={
                'db_table': 'thoitiet_diemden',
                'ordering': ['destination', 'month'],
                'unique_together': {('destination', 'month')},
            },
        ),
    ]
