# Generated by Django 5.1.1 on 2025-10-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTurn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_user', models.TextField()),
                ('text_ai', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['created_at'], name='app_chattur_created_2d9f9d_idx')],
            },
        ),
    ]
