# Generated by Django 5.1.1 on 2025-12-09 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='ten', max_length=255)),
                ('short_description', models.TextField(blank=True, db_column='mo_ta_ngan')),
                ('location', models.CharField(blank=True, db_column='khu_vuc', max_length=255)),
                ('latitude', models.FloatField(blank=True, db_column='vi_do', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='kinh_do', null=True)),
                ('image_url', models.URLField(blank=True, db_column='url_anh', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ngay_tao')),
            ],
            options={
                'db_table': 'diemden',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='ten', max_length=255)),
                ('type', models.CharField(choices=[('restaurant', 'Nhà hàng'), ('street_food', 'Quán ăn đường phố'), ('cafe', 'Cafe'), ('other', 'Khác')], db_column='loai_hinh', default='restaurant', max_length=50)),
                ('address', models.CharField(blank=True, db_column='dia_chi', max_length=255)),
                ('price_range', models.CharField(blank=True, db_column='gia_tham_khao', max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, db_column='url_anh', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ngay_tao')),
                ('destination', models.ForeignKey(db_column='diemden', on_delete=django.db.models.deletion.CASCADE, related_name='food_places', to='app.destination')),
            ],
            options={
                'db_table': 'anuong',
                'ordering': ['destination', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='ten', max_length=255)),
                ('address', models.CharField(blank=True, db_column='dia_chi', max_length=255)),
                ('price_range', models.CharField(blank=True, db_column='gia_tham_khao', max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, db_column='url_anh', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ngay_tao')),
                ('destination', models.ForeignKey(db_column='diemden', on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='app.destination')),
            ],
            options={
                'db_table': 'khachsan',
                'ordering': ['destination', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='tieu_de', max_length=255)),
                ('summary', models.TextField(blank=True, db_column='tong_quan')),
                ('total_days', models.PositiveSmallIntegerField(db_column='so_ngay', help_text='Tổng số ngày trong lịch trình')),
                ('budget_min', models.DecimalField(blank=True, db_column='chi_phi_tu', decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, db_column='chi_phi_den', decimal_places=2, max_digits=12, null=True)),
                ('travel_style', models.CharField(blank=True, db_column='phong_cach', help_text='Ví dụ: nghỉ dưỡng, khám phá, ẩm thực...', max_length=50)),
                ('source_type', models.CharField(choices=[('sample', 'Lịch trình mẫu'), ('ai', 'Lịch trình AI gợi ý'), ('custom', 'Lịch trình tùy chỉnh')], db_column='nguon', default='sample', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Công khai'), ('archived', 'Lưu trữ')], db_column='trang_thai', default='published', max_length=20)),
                ('is_fixed', models.BooleanField(db_column='co_dinh', default=False, help_text='Lịch trình mẫu cố định, chỉ admin được sửa')),
                ('is_public', models.BooleanField(db_column='cong_khai', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ngay_tao')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='ngay_cap_nhat')),
                ('base_itinerary', models.ForeignKey(blank=True, db_column='lichtrinh_goc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_itineraries', to='app.itinerary')),
                ('main_destination', models.ForeignKey(blank=True, db_column='diemden_chinh', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_itineraries', to='app.destination')),
                ('user', models.ForeignKey(blank=True, db_column='nguoidung', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lichtrinh',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(db_column='ngay', help_text='Ngày thứ mấy trong lịch trình (1,2,3,...)')),
                ('part_of_day', models.CharField(choices=[('morning', 'Buổi sáng'), ('afternoon', 'Buổi chiều'), ('evening', 'Buổi tối'), ('full_day', 'Cả ngày')], db_column='buoi', max_length=20)),
                ('activity_title', models.CharField(blank=True, db_column='tieu_de_hoat_dong', max_length=255)),
                ('activity_description', models.TextField(blank=True, db_column='mo_ta_hoat_dong')),
                ('order', models.PositiveIntegerField(db_column='thu_tu', default=1, help_text='Thứ tự trong cùng 1 buổi của ngày đó')),
                ('destination', models.ForeignKey(db_column='diemden', on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_destinations', to='app.destination')),
                ('itinerary', models.ForeignKey(db_column='lichtrinh', on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_destinations', to='app.itinerary')),
            ],
            options={
                'db_table': 'lichtrinh_diemden',
                'ordering': ['itinerary', 'day_number', 'part_of_day', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destinations',
            field=models.ManyToManyField(blank=True, related_name='itineraries', through='app.ItineraryDestination', to='app.destination'),
        ),
        migrations.CreateModel(
            name='ChatTurn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_user', models.TextField(db_column='noi_dung_nguoi_dung')),
                ('text_ai', models.TextField(db_column='noi_dung_ai')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ngay_tao')),
                ('user', models.ForeignKey(blank=True, db_column='nguoidung', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'luot_chat',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['created_at'], name='luot_chat_ngay_ta_2276c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(db_column='thang', help_text='Tháng trong năm (1-12)')),
                ('note', models.TextField(blank=True, db_column='ghi_chu', help_text='Ghi chú tổng quan: nên đi/không nên đi, thời tiết thế nào')),
                ('destination', models.ForeignKey(db_column='diemden', on_delete=django.db.models.deletion.CASCADE, related_name='weather_infos', to='app.destination')),
            ],
            options={
                'db_table': 'thoitiet_diemden',
                'ordering': ['destination', 'month'],
                'unique_together': {('destination', 'month')},
            },
        ),
    ]
