# Generated by Django 5.1.1 on 2025-12-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiitinerarydraft',
            name='accepted_itinerary',
        ),
        migrations.RemoveField(
            model_name='aiitinerarydraft',
            name='ai_parsed',
        ),
        migrations.AddField(
            model_name='aiitinerarydraft',
            name='ai_payload',
            field=models.JSONField(blank=True, db_column='ai_payload', null=True),
        ),
    ]
