# Generated by Django 5.1.1 on 2025-12-28 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_aiitinerarydraft_accepted_itinerary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='destination_airport',
            field=models.ForeignKey(blank=True, db_column='sanbay_den', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_itineraries', to='app.airport'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destination_destination',
            field=models.ForeignKey(blank=True, db_column='diem_den', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_itineraries', to='app.destination'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='flight_segments',
            field=models.ManyToManyField(blank=True, db_table='lichtrinh_changbay', related_name='itineraries', to='app.flightsegment'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='origin_airport',
            field=models.ForeignKey(blank=True, db_column='sanbay_di', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_itineraries', to='app.airport'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='origin_destination',
            field=models.ForeignKey(blank=True, db_column='diem_di', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_itineraries', to='app.destination'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='services',
            field=models.ManyToManyField(blank=True, db_table='lichtrinh_dichvu', related_name='itineraries', to='app.service'),
        ),
    ]
