# Generated by Django 5.1.1 on 2025-12-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_itinerary_destination_airport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiitinerarydraft',
            name='is_public',
            field=models.BooleanField(db_column='cong_khai', default=False),
        ),
    ]
