# Generated by Django 5.1.1 on 2025-12-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_aiitinerarydraft_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiitinerarydraft',
            name='share_requested',
            field=models.BooleanField(db_column='yeu_cau_chia_se', default=False),
        ),
    ]
