# Generated by Django 5.1.1 on 2025-12-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_aiitinerarydraft_share_requested'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itineraryreview',
            name='uniq_danhgia_lichtrinh_nguoidung',
        ),
    ]
