# Generated by Django 5.1.1 on 2025-12-28 14:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_itineraryreview_uniq_danhgia_lichtrinh_nguoidung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDraftReview',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(db_column='so_sao', help_text='So sao 1-5 cho AI itinerary', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, db_column='noi_dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ngay_tao')),
                ('draft', models.ForeignKey(db_column='ai_lichtrinh', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.aiitinerarydraft')),
                ('user', models.ForeignKey(db_column='nguoidung', on_delete=django.db.models.deletion.CASCADE, related_name='ai_itinerary_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_danhgia',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['draft'], name='ai_danhgia_ai_lich_78fbb1_idx'), models.Index(fields=['user'], name='ai_danhgia_nguoidu_2c576a_idx'), models.Index(fields=['created_at'], name='ai_danhgia_ngay_ta_435c32_idx'), models.Index(fields=['rating'], name='ai_danhgia_so_sao_1eec73_idx')],
            },
        ),
    ]
