# Generated by Django 5.1.1 on 2025-12-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_update_itinerary_part_of_day_vn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarydestination',
            name='part_of_day',
            field=models.CharField(choices=[('s?ng', 'Bu?i s?ng'), ('chi?u', 'Bu?i chi?u'), ('t?i', 'Bu?i t?i'), ('c? ng?y', 'C? ng?y')], db_column='buoi', max_length=20),
        ),
    ]
