# Generated by Django 5.1.1 on 2025-12-30 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_itinerarydestination_part_of_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="airports",
                db_column="diemden",
                help_text="Optional link to a destination.",
                to="app.destination",
            ),
        ),
        migrations.AddIndex(
            model_name="airport",
            index=models.Index(fields=["destination"], name="sanbay_destination_idx"),
        ),
    ]
