# Generated by Django 5.1.1 on 2026-01-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_add_airport_destination'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='airport',
            new_name='sanbay_diemden_04c67a_idx',
            old_name='sanbay_destination_idx',
        ),
    ]
