# Generated by Codex on 2026-01-03

from django.db import migrations, models


def forwards(apps, schema_editor):
    ItineraryDestination = apps.get_model("app", "ItineraryDestination")
    mapping = {
        "morning": "sáng",
        "afternoon": "chiều",
        "evening": "tối",
        "full_day": "cả ngày",
        "s?ng": "sáng",
        "chi?u": "chiều",
        "t?i": "tối",
        "c? ng?y": "cả ngày",
    }
    for old, new in mapping.items():
        ItineraryDestination.objects.filter(part_of_day=old).update(part_of_day=new)


def backwards(apps, schema_editor):
    ItineraryDestination = apps.get_model("app", "ItineraryDestination")
    mapping = {
        "sáng": "s?ng",
        "chiều": "chi?u",
        "tối": "t?i",
        "cả ngày": "c? ng?y",
    }
    for old, new in mapping.items():
        ItineraryDestination.objects.filter(part_of_day=old).update(part_of_day=new)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_rename_sanbay_destination_idx_sanbay_diemden_04c67a_idx"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="itinerarydestination",
            name="part_of_day",
            field=models.CharField(
                choices=[
                    ("sáng", "Buổi sáng"),
                    ("chiều", "Buổi chiều"),
                    ("tối", "Buổi tối"),
                    ("cả ngày", "Cả ngày"),
                ],
                db_column="buoi",
                max_length=20,
            ),
        ),
    ]
